### ISSUE TITLE
`play` doesn't work with lazy evaluation

### ISSUE THREAD

**Issue by turion** [Euterpea/Euterpea#12]
One would ideally want to play infinitely long music like
```
let somenote = ( Prim $ Note en ((C,5) :: Pitch) ) :+: somenote
play somenote
```
But this doesn't work, it tries to evaluate the infinite thunk first, before it would start playing. The same issue arises with `repeatM`.

**Comment by santolucito** [comment]
See Euterpea.ExperimentalPlay for new functionality to fix this
