### ISSUE TITLE
Can't install with ghc 7.10.1 (due to dependencies)

### ISSUE THREAD

**Issue by the-drunk-coder** [Euterpea/Euterpea#19]
I know that this is not really your fault, but maybe you know a workaround or something ...

The dependecies CCA and UISF can't be compiled with ghc 7.10.1, seemingly due to changes 
in Template Haskell. Thus, Euterpea as a whole can't be installed with ghc 7.10.1 ...

**Comment by donya** [comment]
Euterpea 1.x (this repository) is not currently being updated. All updates are currently happening within the Euterpea 2 repository, although it is possible that the two repositories may be merged eventually once Euterpea 2 is ready for hackage. Euterpea 2 no longer depends on UISF and CCA, and the MUI functionality that required UISF has been moved to the newer HSoM library.
