### ISSUE TITLE
The folder "HSoM/Pics" should be renamed to "HSoM/pics", notice lowercase 'p'

### ISSUE THREAD

**Issue by acardona** [Euterpea/Euterpea#21]
Or change every single lhs to refer to "Pics" instead.

My guess is that the tester uses a case-insensitive file system such as the default in MacOSX.

A quick workaround: create symbolic link "pics" to "Pics" within HSoM folder.

**Comment by donya** [comment]
Euterpea 1.x (this repository) is not currently being updated. All updates are currently happening within the Euterpea 2 repository, although it is possible that the two repositories may be merged eventually once Euterpea 2 is ready for hackage. Euterpea 2 no longer includes the textbook source.
