### ISSUE TITLE
MakeTex.bat has incorrect line break symbols for linux

### ISSUE THREAD

**Issue by acardona** [Euterpea/Euterpea#22]
A quick trivial workaround is to open the file in vim, copy its contents with the mouse rather than the internal vim copying routines, and then paste into a new buffer or into gedit, and save.

Otherwise every .tex file is written as .tex?, which prevents them from being found by further commands in MakeTex.bat.

**Comment by donya** [comment]
Euterpea 1.x (this repository) is not currently being updated. All updates are currently happening within the Euterpea 2 repository, although it is possible that the two repositories may be merged eventually once Euterpea 2 is ready for hackage.

As of Euterpea 2, the HSoM textbook source and corresponding batch files are no longer part of the repository.
