### ISSUE TITLE
Build failure with GHC 7.10 (GLFW)

### ISSUE THREAD

**Issue by dalejordan** [Euterpea/Euterpea#23]
It looks like GLFW needs updating for 7.10 due to the AMP changes.  I get 3 diagnostics for lack of an Applicative instance for Monads.  I don't know why openGL is required for most things, so maybe there is a workaround.

**Comment by donya** [comment]
Euterpea 1.x (this repository) is not currently being updated. All updates are currently happening within the Euterpea 2 repository, although it is possible that the two repositories may be merged eventually once Euterpea 2 is ready for hackage. Euterpea 2 no longer depends on GLFW.
