### ISSUE TITLE
Update Euterpea version when API changes

### ISSUE THREAD

**Issue by mzero** [Euterpea/Euterpea#28]
Some Euterpea APIs have changed in backward incompatible ways over the last two years. For example, all the functions in `Euterpea.IO.MIDI.MidiIO` dealing with devices have changed pretty drastically.

When such changes are made, the version number of Euterpea should be bumped (see [PVP](https://wiki.haskell.org/Package_versioning_policy)). If it isn't, then it become impossible for code using Euterpea to either create a proper dependency so that it either it only compiles against the version of the API that it is written to, or have conditional code that can adapt to the version of Euterpea it is compiled against.

**Comment by dwincort** [comment]
All true, and the version number most certainly will be bumped when we make our next release to hackage.  That said, we have not been in the habit of bumping the version number for github builds.

... I'm not actually sure *why* we're not in that habit as it seems like a good idea to bump at least the minor version number when the github build is even one commit ahead of the hackage release.  And of course, once we made breaking changes, we could bump the major number.

I'll bump the version number in my next commit (which will also address the init issue you mentioned).

Thanks for pointing this out.

**Comment by dwincort** [comment]
Pushed, and I'll make sure to bump versions earlier from now on.
